# Generated by Django 5.0.6 on 2026-03-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_service_estimated_duration_minutes_service_price"),
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeritem",
            name="leistung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="angebotspositionen",
                to="company.service",
                verbose_name="Leistung",
            ),
        ),
        migrations.AddField(
            model_name="offeritem",
            name="verschmutzungsgrad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="angebotspositionen",
                to="company.soilinglevel",
                verbose_name="Verschmutzungsgrad",
            ),
        ),
        migrations.AddField(
            model_name="offeritem",
            name="zuschlag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="angebotspositionen",
                to="company.surcharge",
                verbose_name="Zuschlag",
            ),
        ),
    ]
