# Generated by Django 5.0.6 on 2026-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_offeritem_leistung_offeritem_verschmutzungsgrad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeritem",
            name="einheit",
            field=models.CharField(
                default="Einheit", max_length=30, verbose_name="Einheit"
            ),
        ),
    ]
