# Generated by Django 5.0.6 on 2026-03-12 17:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auftragsnummer",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        unique=True,
                        verbose_name="Auftragsnummer",
                    ),
                ),
                (
                    "auftragsart",
                    models.CharField(max_length=120, verbose_name="Auftragsart"),
                ),
                ("leistungen", models.TextField(verbose_name="Leistungen")),
                (
                    "verschmutzungsgrad",
                    models.CharField(
                        choices=[
                            ("leicht", "Leicht"),
                            ("normal", "Normal"),
                            ("stark", "Stark"),
                            ("extrem", "Extrem"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Verschmutzungsgrad",
                    ),
                ),
                (
                    "zuschlaege",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Zuschläge (€)",
                    ),
                ),
                ("preisberechnung", models.TextField(verbose_name="Preisberechnung")),
                (
                    "gesamtpreis",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gesamtpreis (€)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("neu", "Neu"),
                            ("geplant", "Geplant"),
                            ("in_bearbeitung", "In Bearbeitung"),
                            ("abgeschlossen", "Abgeschlossen"),
                            ("abgerechnet", "Abgerechnet"),
                            ("storniert", "Storniert"),
                        ],
                        default="neu",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "termin",
                    models.DateTimeField(blank=True, null=True, verbose_name="Termin"),
                ),
                (
                    "interne_notizen",
                    models.TextField(blank=True, verbose_name="Interne Notizen"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auftraege",
                        to="customers.customer",
                        verbose_name="Kunde",
                    ),
                ),
                (
                    "mitarbeiter",
                    models.ManyToManyField(
                        blank=True,
                        related_name="auftraege",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auftrag",
                "verbose_name_plural": "Aufträge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bild", models.ImageField(upload_to="orders/", verbose_name="Bild")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auftrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilder",
                        to="orders.order",
                        verbose_name="Auftrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auftragsbild",
                "verbose_name_plural": "Auftragsbilder",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
