# Generated by Django 5.0.6 on 2026-03-13 06:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_service_estimated_duration_minutes_service_price"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderimage",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Auftragsdatei",
                "verbose_name_plural": "Auftragsdateien",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="verschmutzungsgrad",
        ),
        migrations.RemoveField(
            model_name="order",
            name="zuschlaege",
        ),
        migrations.AddField(
            model_name="order",
            name="gesamtzeit_minuten",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Gesamtzeit (Minuten)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auftraege",
                to="company.ordertype",
                verbose_name="Auftragsart (Stammdaten)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="auftragsart",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Auftragsart"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="gesamtpreis",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Gesamtpreis (€)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="leistungen",
            field=models.TextField(blank=True, verbose_name="Leistungen"),
        ),
        migrations.AlterField(
            model_name="order",
            name="preisberechnung",
            field=models.TextField(blank=True, verbose_name="Preisberechnung"),
        ),
        migrations.AlterField(
            model_name="orderimage",
            name="bild",
            field=models.FileField(upload_to="orders/", verbose_name="Datei"),
        ),
        migrations.CreateModel(
            name="OrderPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("neu", "Neu"),
                            ("geplant", "Geplant"),
                            ("in_bearbeitung", "In Bearbeitung"),
                            ("abgeschlossen", "Abgeschlossen"),
                            ("storniert", "Storniert"),
                        ],
                        default="neu",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Einzelpreis (€)",
                    ),
                ),
                (
                    "geschaetzte_dauer_minuten",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dauer (Minuten)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auftrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="orders.order",
                        verbose_name="Auftrag",
                    ),
                ),
                (
                    "leistung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auftragspositionen",
                        to="company.service",
                        verbose_name="Leistung",
                    ),
                ),
                (
                    "verschmutzungsgrad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auftragspositionen",
                        to="company.soilinglevel",
                        verbose_name="Verschmutzungsgrad",
                    ),
                ),
                (
                    "zuschlag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auftragspositionen",
                        to="company.surcharge",
                        verbose_name="Zuschlag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auftragsposition",
                "verbose_name_plural": "Auftragspositionen",
            },
        ),
    ]
