# Generated by Django 5.0.6 on 2026-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderposition",
            name="einheit",
            field=models.CharField(
                default="Einheit", max_length=30, verbose_name="Einheit"
            ),
        ),
    ]
