# Generated by Django 5.0.6 on 2026-03-12 17:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verkaufsnummer",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, unique=True
                    ),
                ),
                (
                    "zahlungsart",
                    models.CharField(
                        choices=[
                            ("karte", "Karte"),
                            ("ueberweisung", "Überweisung"),
                            ("rechnung", "Rechnung"),
                        ],
                        max_length=20,
                        verbose_name="Zahlungsart",
                    ),
                ),
                (
                    "gesamtbetrag",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mitarbeiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verkaeufe",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verkauf",
                "verbose_name_plural": "Verkäufe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menge", models.PositiveIntegerField(default=1)),
                ("einzelpreis", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gesamtpreis", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verkaufspositionen",
                        to="catalog.article",
                    ),
                ),
                (
                    "verkauf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="checkout.sale",
                        verbose_name="Verkauf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verkaufsposition",
                "verbose_name_plural": "Verkaufspositionen",
            },
        ),
    ]
