# Generated by Django 5.0.6 on 2026-03-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="kunde",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verkaeufe",
                to="customers.customer",
                verbose_name="Kunde",
            ),
        ),
    ]
