# Generated by Django 5.0.6 on 2026-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kundennummer",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        unique=True,
                        verbose_name="Kundennummer",
                    ),
                ),
                ("vorname", models.CharField(max_length=120, verbose_name="Vorname")),
                ("nachname", models.CharField(max_length=120, verbose_name="Nachname")),
                ("strasse", models.CharField(max_length=255, verbose_name="Straße")),
                (
                    "hausnummer",
                    models.CharField(max_length=20, verbose_name="Hausnummer"),
                ),
                ("plz", models.CharField(max_length=10, verbose_name="PLZ")),
                ("ort", models.CharField(max_length=120, verbose_name="Ort")),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kunde",
                "verbose_name_plural": "Kunden",
                "ordering": ["nachname", "vorname"],
            },
        ),
    ]
