# Generated by Django 5.0.6 on 2026-03-12 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rechnungsnummer",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        unique=True,
                        verbose_name="Rechnungsnummer",
                    ),
                ),
                (
                    "rechnungsdatum",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Rechnungsdatum",
                    ),
                ),
                (
                    "faellig_am",
                    models.DateField(blank=True, null=True, verbose_name="Fällig am"),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Betrag"
                    ),
                ),
                (
                    "zahlungsstatus",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("teilweise_bezahlt", "Teilweise bezahlt"),
                            ("bezahlt", "Bezahlt"),
                            ("ueberfaellig", "Überfällig"),
                            ("storniert", "Storniert"),
                        ],
                        default="offen",
                        max_length=30,
                        verbose_name="Zahlungsstatus",
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auftrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechnungen",
                        to="orders.order",
                        verbose_name="Auftrag",
                    ),
                ),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rechnungen",
                        to="customers.customer",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "ordering": ["-rechnungsdatum", "-rechnungsnummer"],
            },
        ),
    ]
