# Generated by Django 5.0.6 on 2026-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_datei",
            field=models.FileField(
                blank=True, null=True, upload_to="invoices/", verbose_name="PDF-Datei"
            ),
        ),
    ]
