# Generated by Django 5.0.6 on 2026-03-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_sale_kunde"),
        ("customers", "0001_initial"),
        ("invoices", "0002_invoice_pdf_datei"),
        ("orders", "0002_alter_orderimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="verkauf",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rechnung",
                to="checkout.sale",
                verbose_name="Verkauf",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("auftrag",), name="unique_invoice_per_order"
            ),
        ),
    ]
