# Generated by Django 5.0.6 on 2026-03-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_verkauf_invoice_unique_invoice_per_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bezahlt_am",
            field=models.DateField(blank=True, null=True, verbose_name="Bezahlt am"),
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(max_length=255, verbose_name="Beschreibung"),
                ),
                (
                    "menge",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="Menge"
                    ),
                ),
                (
                    "einheit",
                    models.CharField(
                        default="Stk.", max_length=30, verbose_name="Einheit"
                    ),
                ),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Einzelpreis (€)"
                    ),
                ),
                (
                    "gesamtpreis",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gesamtpreis (€)"
                    ),
                ),
                (
                    "sortierung",
                    models.PositiveIntegerField(default=0, verbose_name="Sortierung"),
                ),
                (
                    "rechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="invoices.invoice",
                        verbose_name="Rechnung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnungsposition",
                "verbose_name_plural": "Rechnungspositionen",
                "ordering": ["sortierung", "id"],
            },
        ),
    ]
