# Generated by Django 5.0.6 on 2026-03-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_invoice_bezahlt_am_invoicelineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unterpositionen",
                to="invoices.invoicelineitem",
                verbose_name="Hauptposition",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="positionscode",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Positionscode"
            ),
        ),
    ]
