# Generated by Django 5.0.6 on 2026-03-13 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("auftrag", "Auftrag"),
                            ("kunde", "Kunde"),
                            ("rechnung", "Rechnung"),
                            ("angebot", "Angebot"),
                            ("dokument", "Dokument"),
                        ],
                        max_length=20,
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(max_length=255, verbose_name="Objekt"),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Aktion")),
                ("details", models.TextField(blank=True, verbose_name="Details")),
                (
                    "from_state",
                    models.CharField(blank=True, max_length=120, verbose_name="Vorher"),
                ),
                (
                    "to_state",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nachher"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="📝", max_length=20, verbose_name="Icon"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ausgeführt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktivität",
                "verbose_name_plural": "Aktivitäten",
                "ordering": ["-created_at"],
            },
        ),
    ]
