# Generated by Django 5.0.6 on 2026-03-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_type",
                    models.CharField(
                        choices=[
                            ("auftrag", "Auftragsnummer"),
                            ("kunde", "Kundennummer"),
                            ("rechnung", "Rechnungsnummer"),
                            ("angebot", "Angebotsnummer"),
                            ("artikel", "Artikelnummer"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Nummernkreis",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, max_length=20, verbose_name="Prefix"),
                ),
                (
                    "start_value",
                    models.PositiveIntegerField(default=1, verbose_name="Startwert"),
                ),
                (
                    "padding",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Stellenanzahl"
                    ),
                ),
                (
                    "separator",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Trennzeichen"
                    ),
                ),
                (
                    "last_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Letzte vergebene Nummer"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nummernkreis",
                "verbose_name_plural": "Nummernkreise",
            },
        ),
    ]
