# Generated by Django 5.0.6 on 2026-03-13 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vertrag", "Vertrag"),
                            ("bericht", "Bericht"),
                            ("rechnung", "Rechnung"),
                            ("vorlage", "Vorlage"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="sonstiges",
                        max_length=30,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="company_documents/", verbose_name="Datei"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hochgeladen am"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firmendokument",
                "verbose_name_plural": "Firmendokumente",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
