# Generated by Django 5.0.6 on 2026-03-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="estimated_duration_minutes",
            field=models.PositiveIntegerField(
                default=60, verbose_name="Geschätzte Dauer (Minuten)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Preis (€)"
            ),
        ),
    ]
