# Generated by Django 5.0.6 on 2026-03-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_service_estimated_duration_minutes_service_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="bank_name",
            field=models.CharField(blank=True, max_length=180, verbose_name="Bankname"),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="bic",
            field=models.CharField(blank=True, max_length=50, verbose_name="BIC"),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="iban",
            field=models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="kleinunternehmerregelung",
            field=models.BooleanField(
                default=True, verbose_name="Kleinunternehmerregelung (§19 UStG)"
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="tax_id",
            field=models.CharField(blank=True, max_length=80, verbose_name="Steuer-ID"),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="website",
            field=models.CharField(blank=True, max_length=255, verbose_name="Webseite"),
        ),
    ]
