# Generated by Django 5.0.6 on 2026-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_companysettings_bank_name_companysettings_bic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="unit",
            field=models.CharField(
                default="Einheit", max_length=30, verbose_name="Einheit"
            ),
        ),
    ]
