# Generated by Django 5.0.6 on 2026-03-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "preis",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preis"
                    ),
                ),
                (
                    "lagerbestand",
                    models.PositiveIntegerField(default=0, verbose_name="Lagerbestand"),
                ),
                (
                    "kategorie",
                    models.CharField(max_length=80, verbose_name="Kategorie"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("felgenreiniger", "🛞 Felgenreiniger"),
                            ("innenreiniger", "🧴 Innenreiniger"),
                            ("mikrofasertuch", "🧽 Mikrofasertuch"),
                            ("politur", "✨ Politur"),
                            ("versiegelung", "🛡️ Versiegelung"),
                        ],
                        max_length=30,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Artikel",
                "verbose_name_plural": "Artikel",
                "ordering": ["name"],
            },
        ),
    ]
