# Generated by Django 5.0.6 on 2026-03-13 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="artikelnummer",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Artikelnummer",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artikelnummer",
                    models.CharField(max_length=64, verbose_name="Artikelnummer"),
                ),
                ("barcode", models.CharField(max_length=64, verbose_name="Barcode")),
                ("menge", models.PositiveIntegerField(verbose_name="Menge")),
                (
                    "notiz",
                    models.CharField(blank=True, max_length=255, verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gebucht am"),
                ),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wareneingaenge",
                        to="catalog.article",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "gebucht_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wareneingaenge",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gebucht von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wareneingang",
                "verbose_name_plural": "Wareneingänge",
                "ordering": ["-created_at"],
            },
        ),
    ]
