# Generated by Django 5.0.6 on 2026-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_populate_article_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="einheit",
            field=models.CharField(
                default="Stück", max_length=30, verbose_name="Einheit"
            ),
        ),
    ]
